TRAINING_DATA = [
    # Infrastructure
    ("Server is down and users cannot connect", "infrastructure"),
    ("Production API unavailable after deployment", "infrastructure"),
    ("High CPU usage on main node", "infrastructure"),
    ("Load balancer health check failing", "infrastructure"),
    ("Container instances not scaling properly", "infrastructure"),
    ("Disk space full on backend server", "infrastructure"),
    ("Network latency causing slow responses", "infrastructure"),
    ("Kubernetes pods stuck in pending state", "infrastructure"),
    ("Service unreachable from internal network", "infrastructure"),
    ("Autoscaling group failed to launch new instances", "infrastructure"),

    # Payment
    ("Payment gateway timeout during checkout", "payment"),
    ("Credit card transaction declined by processor", "payment"),
    ("Invoice generation failing for some customers", "payment"),
    ("Duplicate charge reported by user", "payment"),
    ("Webhook from payment provider not received", "payment"),
    ("Currency conversion issue in billing", "payment"),
    ("Refund process not updating payment status", "payment"),
    ("3D secure verification failing", "payment"),
    ("Payment confirmation email not sent", "payment"),
    ("Checkout page throwing 502 error", "payment"),

    # Authentication
    ("Unable to login with correct credentials", "authentication"),
    ("Password reset link expired", "authentication"),
    ("Users getting 401 unauthorized error", "authentication"),
    ("SSO login not redirecting correctly", "authentication"),
    ("OAuth token validation failed", "authentication"),
    ("Session timeout too short for admin users", "authentication"),
    ("MFA code rejected even when valid", "authentication"),
    ("User locked out after too many attempts", "authentication"),
    ("Login API returning 500 error", "authentication"),
    ("User registration confirmation email missing", "authentication"),

    # Feature Request
    ("Add a new endpoint for ticket metrics", "feature_request"),
    ("Request for CSV export of user activity", "feature_request"),
    ("Add filter option on incident dashboard", "feature_request"),
    ("Enable dark mode in web interface", "feature_request"),
    ("Add Slack integration for alerts", "feature_request"),
    ("Include uptime report in weekly summary", "feature_request"),
    ("Allow bulk update for tickets", "feature_request"),
    ("Add search by tag functionality", "feature_request"),
    ("Provide REST API for configuration changes", "feature_request"),
    ("Add role-based access control to admin panel", "feature_request"),

    # Database
    ("Database latency causing delays", "database"),
    ("Slow query detected in analytics service", "database"),
    ("Replication lag between primary and replica", "database"),
    ("Connection pool exhausted under load", "database"),
    ("Database backup failed last night", "database"),
    ("Index missing on user_id column", "database"),
    ("Transaction deadlock detected", "database"),
    ("Read-only mode enabled unexpectedly", "database"),
    ("Data inconsistency found in audit logs", "database"),
    ("Database connection timeout errors increasing", "database"),

    # Frontend
    ("User interface button is not responsive", "frontend"),
    ("Dropdown menu not displaying options", "frontend"),
    ("Broken layout on mobile devices", "frontend"),
    ("Text overlapping on dashboard view", "frontend"),
    ("UI not updating after data refresh", "frontend"),
    ("Chart rendering incorrectly in Safari", "frontend"),
    ("Missing loading spinner on data fetch", "frontend"),
    ("Color contrast issue in dark mode", "frontend"),
    ("Tooltip not appearing on hover", "frontend"),
    ("Page not scrolling to selected section", "frontend"),

    # Configuration
    ("Increase timeout for external API calls", "configuration"),
    ("Environment variables not loaded in staging", "configuration"),
    ("Incorrect port number in service config", "configuration"),
    ("Logging level set too high in production", "configuration"),
    ("Config file missing required parameter", "configuration"),
    ("Feature flag not enabled for beta users", "configuration"),
    ("SSL verification disabled in test environment", "configuration"),
    ("Cache size configuration too low", "configuration"),
    ("API key not set in environment", "configuration"),
    ("CORS settings blocking valid requests", "configuration"),

    # Bug
    ("App crashes when loading dashboard", "bug"),
    ("Unexpected null pointer in error handler", "bug"),
    ("UI freezes after clicking save button", "bug"),
    ("Memory leak detected in background job", "bug"),
    ("Duplicate records created after submission", "bug"),
    ("File upload not completing successfully", "bug"),
    ("Form validation failing on correct input", "bug"),
    ("Race condition causing inconsistent state", "bug"),
    ("Crash when opening settings page", "bug"),
    ("Unexpected behavior after updating version", "bug"),

    # Security
    ("SSL certificate expired on staging", "security"),
    ("Unauthorized access attempt detected", "security"),
    ("Password stored in plain text", "security"),
    ("XSS vulnerability found in comments section", "security"),
    ("Security scan flagged outdated dependency", "security"),
    ("Firewall rules blocking internal traffic", "security"),
    ("Brute force login attempts detected", "security"),
    ("Sensitive logs exposed in console output", "security"),
    ("Missing HTTP security headers", "security"),
    ("Access token leaked in client-side code", "security"),

    # Notification
    ("Email notifications not being sent", "notification"),
    ("Slack alerts delayed by several minutes", "notification"),
    ("Push notification service unreachable", "notification"),
    ("SMS delivery failing for password resets", "notification"),
    ("Notification preferences not saving properly", "notification"),
    ("Duplicate emails sent for same event", "notification"),
    ("In-app alert not dismissed after read", "notification"),
    ("Webhook event triggered multiple times", "notification"),
    ("Email subject line missing details", "notification"),
    ("Notification queue backlog increasing", "notification"),
]
