name: Backend CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:15
        env:
          POSTGRES_USER: smartops_user
          POSTGRES_PASSWORD: smartops_pass
          POSTGRES_DB: smartops_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U smartops_user"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run unit tests
      working-directory: app/
      env:
        POSTGRES_USER: smartops_user
        POSTGRES_PASSWORD: smartops_pass
        POSTGRES_DB: smartops_db
        POSTGRES_HOST: db
        POSTGRES_PORT: 5432
        DATABASE_URL: postgresql://smartops_user:smartops_pass@db:5432/smartops_db
        PYTHONPATH: ${{ github.workspace }}
      run: |
        pytest -q tests/
